# -*- coding: utf-8 -*-
"""Final_capstone

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bhqZ6LQDRPjjd_8c9FVwtkPZ-aaX1bpj
"""

import dlt
from pyspark.sql.functions import col, sum, current_timestamp

@dlt.table(name="bronze_patients")

def bronze_patients():
    data = [
        (101,"Arjun Reddy","Hyderabad","Cardiology",5000,1),
        (102,"Sneha Kapoor","Delhi","Orthopedics",3000,2),
        (103,"Rahul Sharma","Mumbai","Dermatology",1500,1),
        (104,"Priya Nair","Bangalore","Cardiology",5000,2),
        (105,"Vikram Singh","Chennai","Neurology",7000,1),
        (106,"Ananya Das","Kolkata","Orthopedics",3000,3),
        (107,"Karan Patel","Ahmedabad","Cardiology",5000,1),
        (108,"Meera Iyer","Bangalore","Dermatology",1500,2)
    ]
    columns = ["visit_id","patient_name","city","department","consultation_fee","tests_count"]
    return spark.createDataFrame(data, columns)

@dlt.table(name="silver_patients")
@dlt.expect("valid_consultation_fee","consultation_fee>0")
def silver_patients():
    df=dlt.read("bronze_patients")
    return df.withColumn(
        "total_cost",
        col("consultation_fee")+col("tests_count")*500
    )

@dlt.table(name="incremental_patient_updates")
def incremental_patient_updates():
    updates = [
        (101,"Arjun Reddy","Hyderabad","Cardiology",6000,2),
        (110,"New Patient","Chennai","Neurology",8000,2)
    ]
    columns = ["visit_id","patient_name","city","department","consultation_fee","tests_count"]
    return spark.createDataFrame(updates,columns) \
        .withColumn("update_time",current_timestamp()) \
        .withColumn("total_cost",col("consultation_fee")+col("tests_count")*500)

dlt.create_streaming_table("silver_patients_incremental")

dlt.apply_changes(
    target="silver_patients_incremental",
    source="incremental_patient_updates",
    keys=["visit_id"],
    sequence_by=col("update_time"),
    stored_as_scd_type=1
)

@dlt.table(name="gold_patients")
def gold_patients():
    df = dlt.read("silver_patients_incremental")
    return df.groupBy("department").agg(
        sum("total_cost").alias("total_revenue")
    )

@dlt.table(name="final_data")
def final_data():
    return dlt.read("silver_patients_incremental")